CC=     gcc -Zomf

CFLAGS= -g -Wall -O3 -DHAVE_MEMCPY

OBJS=   mp3gain.o apetag.o gain_analysis.o rg_error.o \
	mpglibDBL/common.o mpglibDBL/dct64_i386.o \
	mpglibDBL/decode_i386.o mpglibDBL/interface.o \
	mpglibDBL/layer3.o mpglibDBL/tabinit.o

all: mp3gain

mp3gain: $(OBJS) mp3gain.def
	$(CC) -o mp3gain.exe $(OBJS) mp3gain.def -lc_omf386 -static -s

clean:
	-del mp3gain.exe *.o mpglibDBL\*.o
